server.port: 8090

spring:
 application:
  name: ecommerce-products
 h2:
  console:
   enabled: true
 jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
 datasource:
  driverClassName: org.h2.Driver
  username: sa
  password: 
  url: jdbc:h2:mem:productsDb;DB_CLOSE_ON_EXIT=FALSE
logging:
  level:
    root: DEBUG
